### ISSUE TITLE
Icons not displayed in Kopf plugin in elasticsearch 2.3

### ISSUE THREAD

**Issue by Mdzaffar** [lmenezes/elasticsearch-kopf#352]
After the upgrade of Elastic search cluster 2.3 and Kopf plugin , I found icon is missing on the page for all links in kopf.

**Comment by lmenezes** [comment]
@Mdzaffar do you get any network errors when loading the page? if you could look in the network console and tell me what you have in there, this would be helpful :)

**Comment by Mdzaffar** [comment]
I got issue only on chrome browser

**Comment by lmenezes** [comment]
have you tried cleaning your cache?

**Comment by nickmaccarthy** [comment]
I have the same issue.  I loaded Kopf in an incognito window in Chrome and I still see no icons.

I am getting 403's for the font-awesome links.  I have no auth setup in my ES cluster so I'm not sure why I am getting those.

**Comment by neverfox** [comment]
Same, there's a `Failed to load resource: the server responded with a status of 403 (Forbidden)` for font-awesome.

**Comment by pricecarl** [comment]
Same with me guys

**Comment by BDeus** [comment]
same with me too

**Comment by Mdzaffar** [comment]
I have cleared the cache, but still icons are not there

**Comment by zdeseb** [comment]
I have the same problem after upgrade to ES 2.3.0

Plus for example Disable/Enable shard allocation doesn't work.
I get following error:
`XMLHttpRequest cannot load http://czprgsest01:9200/_cluster/settings. Method PUT is not allowed by Access-Control-Allow-Methods in preflight response.`

**Comment by KptnKMan** [comment]
I'm also experiencing this issue in ES 2.3.1.
Does anyone have any workaround or indication what is happening?

**Comment by lmenezes** [comment]
hum, I think there is a mix of issues here.

@zdeseb you need to enable CORS on the ES config and then this should be solved.

For the rest, I have tried reproducing this issue without luck. Are you guys just running kopf on a downloaded ES instance, with the plugin installed? Or are you doing something different?

**Comment by zdeseb** [comment]
It's not ES config problem, see following link (there is something wrong with CORS in ES last versions)

https://www.elastic.co/guide/en/elasticsearch/reference/current/breaking-changes-2.3.html#_cors_support_broken_in_2_3_0_and_2_3_1

**Comment by lmenezes** [comment]
oh, in this case, there is not much to be done here(except having the plugin installed on the instance itself, then there is no CORS issue)

**Comment by KptnKMan** [comment]
Thanks all, hopefully a release of ES 2.3.2 is coming soon.

**Comment by KptnKMan** [comment]
For anyone who might be still experiencing this issue, I *think* I managed to work around the issue by removing `http.cors.enabled` from my ES `elasticsearch.yml` config file.

**_Screenshots taken from the same node:_**

**Before:**
![image](https://cloud.githubusercontent.com/assets/12234043/14493247/bdadc84a-0184-11e6-8883-1e100b3c48e5.png)

**After:**
![image](https://cloud.githubusercontent.com/assets/12234043/14493290/046a2120-0185-11e6-9358-6f79b93eb911.png)

**Apparently its no longer required** but _I'm not going to pretend I know why exactly this is at the moment._

**This also seems to fix curl GET issues for me.**

@lmenezes do you have any idea why this appears to work?
Thanks in advance.

**Comment by lmenezes** [comment]
Not really sure, but I suppose if you remove this setting and this still works, it means you are running kopf installed on your node, right?

**Comment by KptnKMan** [comment]
I am running it locally on the ES node, yes.

I have done some extra digging and found that if I add the `http.cors.allow-origin: "*"` setting, then I can leave `http.cors.enabled: true` enabled.

This should help someone that needs this to work.

**I do, however, understand that `http.cors.allow-origin: "*"` is insecure, according to [elastics docs](https://www.elastic.co/guide/en/elasticsearch/reference/current/modules-http.html).**

Any idea how I can lock this to the local host?
The recommended setting `/https?:\/\/localhost(:[0-9]+)?/` doesnt seem to work for me, but `"*"` does.

Thanks.

**Comment by up-town-down** [comment]
I think the CORS setting is very specific as to the allowed URL, are you actually accessing it via http://localhost/ i.e. your browser is on the same server? Also I've had issues - even with the CORS header set - in Firefox, but not in Chrome for example. Have you tested multiple Browsers?

**Comment by drorata** [comment]
I can confirm that disabling `http.cors.enabled` resolved the issue. It also fixed another issue I had with Sense. Thanks!
